spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mxy.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microservice-product-config-bus111
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka6001.com:6001/eureka/
    instance:
      instanceId: ${spring.application.name}:${server.port}
      prefer-ip-address: true
emp:
  name: zhangsan
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mxy.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod
  application:
    name: microservice-product-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka6001.com:6001/eureka/
    instance:
      instanceId: ${spring.application.name}:${server.port}
      prefer-ip-address: true
